apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        io.kompose.network/tracing: "true"
        app: backend
    spec:
      containers:
        - env:
            - name: JAEGER_HOST
              value: jaeger
            - name: JAEGER_PORT
              value: JAEGER_PORT
            - name: JAEGER_SERVICE_NAME
              value: backend
          name: backend
          image: jairtonjr/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   prometheus.io/port: "9090"
  #   prometheus.io/scrape: "true"
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend 
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   name: backend
#   namespace: monitoring
#   labels:
#     app: backend
#     release: prometheus
# spec:
#   selector:
#     matchLabels:
#       app: backend
#   endpoints:
#   - port: backend
#     path: /metrics
#     interval: 15s
#   namespaceSelector:
#     matchNames:
#     - default