{
 "title": "MyDashBoard-Uptime_ResponseTime",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{namespace=\"default\", status=\"200\"}[1d])/rate(flask_http_request_duration_seconds_count{namespace=\"default\", status=\"200\"}[1d])",
     "legendFormat": "{{job}} - {{path}}"
    }
   ]
  },
  {
   "title": "CPU usage by POD",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"default\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors by service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(sum_over_time(flask_http_request_total{status=~\"[4-5]0[0-9]\"}[1d]))by(job,status,path))by(job,status,path)"
    }
   ]
  },
  {
   "title": "Memory usage by POD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"default\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(flask_http_request_total{namespace=\"default\"}[1m]))"
    }
   ]
  }
 ]
}